# Generated by Django 2.1.7 on 2019-05-11 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190511_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_h', models.PositiveIntegerField(default=200)),
                ('image_w', models.PositiveIntegerField(default=200)),
                ('done_time', models.TimeField(auto_now_add=True)),
                ('image_done', models.ImageField(height_field=models.PositiveIntegerField(default=200), upload_to='img_done/', width_field=models.PositiveIntegerField(default=200))),
                ('upload_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UploadImage')),
            ],
        ),
    ]
